# Generated by Django 4.1.5 on 2023-02-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_regmodel_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pic',
            field=models.ImageField(null=True, upload_to='', verbose_name='profile pic'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Enter Email'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='experience',
            field=models.IntegerField(verbose_name='Enter Experience'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='first',
            field=models.CharField(max_length=100, verbose_name='Enter First Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='last',
            field=models.CharField(max_length=100, verbose_name='Enter Last Name'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='password',
            field=models.CharField(max_length=100, verbose_name='Enter password'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='username',
            field=models.CharField(max_length=100, verbose_name='Enter UserName'),
        ),
    ]
