# Generated by Django 4.1.5 on 2023-02-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_staff_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='pic',
            field=models.ImageField(null=True, upload_to='profile_pic'),
        ),
    ]
